version: "3.8"
services:
       cms-app:
           container_name: CMS-app
           image: cms-docker
           restart: unless-stopped
           build: .
           ports:
             - "5000:3000"
           links:
             - mongo
           depends_on:
             - mongo
           environment:
           - DB_HOST=mongo
       mongo:
             container_name: mongo
             image: mongo
             environment:
             - PUID=1000
             - PGID=1000
             volumes:
               - mongodb:/data/db
             ports:
               - '27017:27017'
volumes:
   mongodb:
